# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * 6"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN_2 }}

          # Options
          user: nonissue
          template: classic
          base: header, repositories
          config_timezone: America/Edmonton
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_languages_indepth: yes
          commits_authoring: andy williams, nonissue, nonissue@users.noreply.github.com
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_habits_charts_type: graph
          plugin_activity: no
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_visibility: all
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_stars: no
          plugin_stars_limit: 4
